language: c
compiler:
  - gcc
before_install:
- sudo apt-get install libgnutls-dev # Otherwise PPA no worky
- sudo add-apt-repository ppa:dns/gnu --yes
- sudo apt-get update
- sudo apt-get install autoconf automake libtool
- sudo apt-get install guile-2.0
- make -f Makefile.dist
install:
- ./configure
- make
script:
- make check
